### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Arinala** [afonari/emc#11]
Dear all,

I am trying to calculate the effective mass using emc-1.50.
It has an error :

Redirecting output to emcpy.out_1501496643
Traceback (most recent call last):
  File "./emc.py", line 426, in <module>
    energies = parse_EIGENVAL_VASP(output_fh, band, len(st))
  File "./emc.py", line 290, in parse_EIGENVAL_VASP
    energies.append(float(line.split()[1])*ev2h)
IndexError: list index out of range

Can someone help me to fix this issue please!

Thank you very much.

**Comment by afonari** [comment]
Can you attach EIGENVAL file?

**Comment by Arinala** [comment]
Dear Prof Fonari,

Thank you for your reply. Please find attached my input file and EIGENVAL
obtained with VASP Medea.

Thank you very much.

Regards

Arinala

2017-07-31 15:52 GMT+02:00 Alexandr Fonari <notifications@github.com>:

**Comment by afonari** [comment]
I don't see the file... and I'm not a professor =)

**Comment by Arinala** [comment]
Oh, I am sorry for this. I have reattached them.
[EIGENVAL.txt](https://github.com/afonari/emc/files/1190842/EIGENVAL.txt)
[input.txt](https://github.com/afonari/emc/files/1190843/input.txt)

**Comment by afonari** [comment]
Your EIGENVAL contains only 4 k-points: 0.0000000E+00  0.0000000E+00  0.0000000E+00
0.2500000E+00  0.0000000E+00  0.0000000E+00
0.5000000E+00  0.0000000E+00  0.0000000E+00
0.2500000E+00  0.2500000E+00  0.0000000E+00

These seems to be form an SCF calculation. You will need to run an NSCF calculations, with KPOINT file prepared by emc.py: https://github.com/afonari/emc#usage point 2: Generate k-point grid (in KPOINT file).

**Comment by Arinala** [comment]
Thank you very much for your assistance. The error is no longer exist. 
But I have another question. The values of the effective mass change with the value of the step size in the input_file. Can you please tell me how to choose the step size?

**Comment by Priyankagarg1991** [comment]
Dear all,
I am using this emc codes for my system, and I got following type of error:
    masses, vecs_cart, vecs_frac, vecs_n = get_eff_masses(m, basis)
  File "/home/pathak/priyanka/emc.py/emc.py", line 437, in get_eff_masses
    em = [ 1.0/eigval[i] for i in range(len(eigval)) ]
ZeroDivisionError: float division by zero

What does it mean??? can anybody fix it??

**Comment by afonari** [comment]
eigval[i] is zero. Can you attach EIGENVAL file? and input command.

**Comment by Priyankagarg1991** [comment]
Ya sure!!

**Comment by Priyankagarg1991** [comment]
[INPUT COMMAND.txt](https://github.com/afonari/emc/files/1884280/INPUT.COMMAND.txt)

[EIGENVAL.txt](https://github.com/afonari/emc/files/1884285/EIGENVAL.txt)

**Comment by afonari** [comment]
Can you also attach the INPCAR?

**Comment by Priyankagarg1991** [comment]
Dear sir,

The INPCAR file is as follows:

0.000 0.000 0.500
0.01
162
V
 23.9207480479305055   -0.0000334263855088   -0.0001340573427983
    -0.0000310523845595   23.8976212655321554    0.0002153020378481
    -0.0000383115481485    0.0000628395429983    6.8003690293269710

**Comment by Priyankagarg1991** [comment]
0.000 0.000 0.000
0.01
162
V
 23.9207480479305055   -0.0000334263855088   -0.0001340573427983
    -0.0000310523845595   23.8976212655321554    0.0002153020378481
    -0.0000383115481485    0.0000628395429983    6.8003690293269710

**Comment by Priyankagarg1991** [comment]
Dear  Fonari ,
I some how understand that the step size is responsible for the KPOINTS generation. Now, how can we fix the step size??

**Comment by afonari** [comment]
Step size is the second line in the INPCAR, in your case is 0.01.

The error appears because one of the eigenvalues is zero, try to increase the step size.

**Comment by Priyankagarg1991** [comment]
Many thanks for your reply. I will try with high step size.

**Comment by Priyankagarg1991** [comment]
Can you please suggest me that how to choose the step size according to
dimension means for 1D, 2D and 3D ? If the system is same but the dimension
is changed so should we use same step size for all the case?

**Comment by afonari** [comment]
I would suggest making it work with at least one step first.

**Comment by Priyankagarg1991** [comment]
OK fine but I have increased the step size from 0.01 to 0.05 then it works
but the values are not matching with the previous values.

**Comment by afonari** [comment]
This is expected.

**Comment by Priyankagarg1991** [comment]
So what should I do??

**Comment by afonari** [comment]
Sorry, I don't know.

**Comment by Priyankagarg1991** [comment]
Ok thanks!!

**Comment by Priyankagarg1991** [comment]
What step size generally you prefer?
